(function(){
'use strict';
const $=id=>document.getElementById(id),canvas=$('game-canvas'),loading=$('loading-screen'),keys=new Set(),joy={x:0,y:0},input={sprint:false};
const H={cash:$('hud-cash'),xp:$('hud-xp'),level:$('hud-level'),wanted:$('hud-wanted'),online:$('hud-online'),vehicle:$('hud-vehicle'),vhp:$('hud-vehicle-hp'),gas:$('hud-vehicle-gas'),mission:$('hud-mission'),fps:$('debug-fps'),pos:$('debug-pos'),chunks:$('debug-chunks'),npcs:$('debug-npcs'),active:$('debug-active-vehicle'),slot:$('debug-save-slot'),dbg:$('debug-online'),err:$('debug-last-error')};
const S={cash:120,xp:0,level:1,wanted:0,slot:'slot1',p:{x:0,y:1.2,z:0,vx:0,vy:0,vz:0,ground:false},car:null,chunks:new Map(),pickups:[],props:[],cars:[],owned:{},got:{},mission:null,last:0};
const prog={collect:0,drive:0,own:0};
const missions=[{id:'courier',name:'Neon Courier',type:'collect',target:5,reward:180,xp:90},{id:'driver',name:'Block Taxi',type:'drive',target:350,reward:220,xp:110},{id:'owner',name:'First Property',type:'own',target:1,reward:260,xp:150}];
let THREE=window.THREE,scene,camera,renderer,clock,avatar,world,mini=$('minimap-canvas')?.getContext('2d'),toastBox=$('reward-popup');
function boot(){if(!THREE){H.err.textContent='Three.js missing';return;}scene=new THREE.Scene();scene.background=new THREE.Color(0x050814);scene.fog=new THREE.Fog(0x050814,70,280);camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,900);renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setSize(innerWidth,innerHeight);clock=new THREE.Clock();world=new THREE.Group();scene.add(world);scene.add(new THREE.HemisphereLight(0x8bdfff,0x150825,1.8));let sun=new THREE.DirectionalLight(0xffffff,1.3);sun.position.set(50,80,30);scene.add(sun);let floor=new THREE.Mesh(new THREE.BoxGeometry(1200,1,1200),mat(0x10162d));floor.position.y=-.55;scene.add(floor);avatar=makeAvatar();scene.add(avatar);bind();buildMissions();load('slot1',false).finally(()=>{loading?.classList.add('hidden');requestAnimationFrame(loop);});}
function mat(c,e=0){return new THREE.MeshStandardMaterial({color:c,emissive:e,roughness:.65});}
function makeAvatar(){let g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(1.4,2.2,.8),mat(0x17f3ff,0x07333d)),h=new THREE.Mesh(new THREE.BoxGeometry(1.05,1.05,1.05),mat(0xffd99a));b.position.y=1.5;h.position.y=3.15;g.add(b,h);return g;}
function rnd(n){return Math.abs(Math.sin(n*999.13)*10000)%1;}
function key(cx,cz){return cx+','+cz;}
function chunks(){let cx=Math.floor(S.p.x/80),cz=Math.floor(S.p.z/80),need=new Set();for(let x=cx-2;x<=cx+2;x++)for(let z=cz-2;z<=cz+2;z++){need.add(key(x,z));if(!S.chunks.has(key(x,z)))chunk(x,z);}for(let [k,o] of S.chunks)if(!need.has(k)){world.remove(o);S.chunks.delete(k);}}
function chunk(cx,cz){let g=new THREE.Group(),bx=cx*80,bz=cz*80,road=mat(0x171b35,0x01020a);for(let i=-1;i<=1;i++){let a=new THREE.Mesh(new THREE.BoxGeometry(80,.06,5),road);a.position.set(bx+40,.04,bz+40+i*24);g.add(a);let b=new THREE.Mesh(new THREE.BoxGeometry(5,.06,80),road);b.position.set(bx+40+i*24,.05,bz+40);g.add(b);}for(let i=0;i<9;i++){let r=rnd(cx*31+cz*17+i),x=bx+8+rnd(i+cx)*64,z=bz+8+rnd(i+cz*2)*64,h=8+(r*36|0),m=new THREE.Mesh(new THREE.BoxGeometry(8+r*12,h,8+rnd(i*3)*10),mat(r>.5?0x232b58:0x1a2045,r>.75?0x061622:0));m.position.set(x,h/2,z);g.add(m);if(r>.77)prop(x,z,cx,cz,i,g);}for(let i=0;i<4;i++)pickup(bx+10+rnd(cx*13+i)*60,bz+10+rnd(cz*19+i)*60,cx,cz,i,g);if((cx+cz)%3===0)car(bx+35,bz+35,g);world.add(g);S.chunks.set(key(cx,cz),g);}
function pickup(x,z,cx,cz,i,g){let id='c'+cx+'_'+cz+'_'+i;if(S.got[id])return;let o=new THREE.Mesh(new THREE.BoxGeometry(1.4,1.4,1.4),mat(0x17f3ff,0x0b6b70));o.position.set(x,1.2,z);o.userData={id,value:25};S.pickups.push(o);g.add(o);}
function prop(x,z,cx,cz,i,g){let id='p'+cx+'_'+cz+'_'+i,o=new THREE.Mesh(new THREE.TorusGeometry(3,.22,8,28),mat(S.owned[id]?0x5ef38c:0xffd166,S.owned[id]?0x123d1f:0x392b00));o.rotation.x=Math.PI/2;o.position.set(x,.35,z);o.userData={id,price:250+Math.abs(cx*37+cz*19+i*50)%500};S.props.push(o);g.add(o);}
function car(x,z,g){let c=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(4.4,1.3,7),mat(0xff3366,0x2a0010)),top=new THREE.Mesh(new THREE.BoxGeometry(3.2,1,3),mat(0x17f3ff,0x062e38));body.position.y=1;top.position.y=2;c.add(body,top);c.position.set(x,.05,z);c.userData={name:'Neon Kart',hp:100,gas:100,lx:x,lz:z};S.cars.push(c);g.add(c);}
function bind(){addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key==='Escape')pause();if(['e','f'].includes(e.key.toLowerCase()))act();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});$('btn-mobile-jump')?.addEventListener('click',jump);$('btn-mobile-interact')?.addEventListener('click',act);$('btn-mobile-unstuck')?.addEventListener('click',()=>{S.p.x=S.p.z=0;S.p.y=2;});$('btn-mobile-pause')?.addEventListener('click',pause);$('btn-mobile-sprint')?.addEventListener('pointerdown',()=>input.sprint=true);$('btn-mobile-sprint')?.addEventListener('pointerup',()=>input.sprint=false);$('btn-mobile-sprint')?.addEventListener('pointercancel',()=>input.sprint=false);$('btn-resume')?.addEventListener('click',pause);$('btn-settings')?.addEventListener('click',()=>show('settings-panel'));$('btn-close-settings')?.addEventListener('click',()=>hide('settings-panel'));$('btn-save')?.addEventListener('click',()=>show('save-panel'));$('btn-load')?.addEventListener('click',()=>load(S.slot,true));$('btn-missions')?.addEventListener('click',()=>show('mission-board'));$('btn-close-missions')?.addEventListener('click',()=>hide('mission-board'));$('btn-export')?.addEventListener('click',exportSave);$('btn-import')?.addEventListener('click',importSave);$('btn-close-save')?.addEventListener('click',()=>hide('save-panel'));document.querySelectorAll('.btn-save-slot').forEach(b=>b.onclick=()=>save(b.dataset.slot,true));document.querySelectorAll('.btn-load-slot').forEach(b=>b.onclick=()=>load(b.dataset.slot,true));joystick();}
function joystick(){let box=$('joystick-container'),stick=$('joystick-stick');if(!box||!stick)return;function mv(t){let r=box.getBoundingClientRect(),dx=t.clientX-r.left-r.width/2,dy=t.clientY-r.top-r.height/2,max=42;joy.x=Math.max(-1,Math.min(1,dx/max));joy.y=Math.max(-1,Math.min(1,dy/max));stick.style.transform='translate('+Math.min(max,Math.abs(dx))*Math.sign(dx)+'px,'+Math.min(max,Math.abs(dy))*Math.sign(dy)+'px)';}box.onpointerdown=e=>{box.setPointerCapture(e.pointerId);mv(e);};box.onpointermove=e=>{if(e.buttons)mv(e);};box.onpointerup=()=>{joy.x=joy.y=0;stick.style.transform='translate(0,0)';};}
function vec(){let x=0,z=0;if(keys.has('w')||keys.has('arrowup'))z--;if(keys.has('s')||keys.has('arrowdown'))z++;if(keys.has('a')||keys.has('arrowleft'))x--;if(keys.has('d')||keys.has('arrowright'))x++;x+=joy.x;z+=joy.y;let l=Math.hypot(x,z)||1;return{x:x/l,z:z/l,on:Math.hypot(x,z)>.05};}
function jump(){if(S.p.ground){S.p.vy=15;S.p.ground=false;}}
function step(dt){chunks();let v=vec();if(keys.has(' '))jump();S.p.sprint=keys.has('shift')||input.sprint;if(S.car)drive(dt,v);else walk(dt,v);pickups();props();mission();cam(dt);map();hud();if(Date.now()-S.last>15000)save(S.slot,false);}
function walk(dt,v){let p=S.p,sp=p.sprint?30:18;if(v.on){p.vx=v.x*sp;p.vz=v.z*sp;}else{p.vx*=.82;p.vz*=.82;}p.vy-=42*dt;p.x+=p.vx*dt;p.z+=p.vz*dt;p.y+=p.vy*dt;if(p.y<1.2){p.y=1.2;p.vy=0;p.ground=true;}avatar.position.set(p.x,p.y-1.2,p.z);if(v.on)avatar.rotation.y=Math.atan2(p.vx,p.vz);}
function drive(dt,v){let c=S.car,d=c.userData;if(v.on&&d.gas>0){c.rotation.y=-Math.atan2(v.x,v.z);c.position.x+=v.x*48*dt;c.position.z+=v.z*48*dt;d.gas=Math.max(0,d.gas-dt*2);prog.drive+=Math.hypot(c.position.x-d.lx,c.position.z-d.lz);d.lx=c.position.x;d.lz=c.position.z;}S.p.x=c.position.x;S.p.z=c.position.z+2;S.p.y=1.2;avatar.position.set(S.p.x,0,S.p.z);}
function near(arr,max){let b=null,bd=max;for(let o of arr){let d=Math.hypot(o.position.x-S.p.x,o.position.z-S.p.z);if(d<bd){b=o;bd=d;}}return b;}
function act(){if(S.car){S.car=null;toast('Exited vehicle');return;}let c=near(S.cars,8);if(c){S.car=c;toast('Entered '+c.userData.name);return;}let p=near(S.props,7);if(p){let id=p.userData.id,price=p.userData.price;if(S.owned[id])return toast('Already owned');if(S.cash<price)return toast('Need $'+price);S.cash-=price;S.owned[id]=true;prog.own=Object.keys(S.owned).length;p.material.color.setHex(0x5ef38c);reward('Property bought',0,40);}}
function pickups(){for(let i=S.pickups.length-1;i>=0;i--){let p=S.pickups[i];p.rotation.y+=.03;p.position.y=1.2+Math.sin(performance.now()/300+i)*.25;if(Math.hypot(p.position.x-S.p.x,p.position.z-S.p.z)<3){S.got[p.userData.id]=true;S.cash+=p.userData.value;S.xp+=20;prog.collect++;p.parent?.remove(p);S.pickups.splice(i,1);toast('+$'+p.userData.value+' data cube');}}}
function props(){S.props.forEach(p=>p.rotation.z+=.01);}
function buildMissions(){let list=$('mission-list');if(!list)return;list.innerHTML='';missions.forEach(m=>{let li=document.createElement('li'),b=document.createElement('button');b.textContent=m.name+' - '+m.target+' '+m.type;b.onclick=()=>{S.mission=m.id;hide('mission-board');toast('Mission started: '+m.name);};li.appendChild(b);list.appendChild(li);});}
function mission(){let m=missions.find(x=>x.id===S.mission);if(!m)return;if((prog[m.type]||0)>=m.target){S.cash+=m.reward;S.xp+=m.xp;reward(m.name+' complete',m.reward,m.xp);S.mission=null;prog[m.type]=0;}}
function cam(dt){camera.position.lerp(new THREE.Vector3(S.p.x,28,S.p.z+42),Math.min(1,dt*4));camera.lookAt(S.p.x,6,S.p.z);}
function hud(){S.level=1+Math.floor(S.xp/250);H.cash.textContent='$'+Math.floor(S.cash);H.xp.textContent=Math.floor(S.xp);H.level.textContent=S.level;H.wanted.textContent=S.wanted;H.online.textContent=window.NeonBlockSaveBackend?.mode||'offline';H.dbg.textContent=H.online.textContent;H.vehicle.textContent=S.car?S.car.userData.name:'On foot';H.vhp.textContent=S.car?S.car.userData.hp:100;H.gas.textContent=S.car?Math.floor(S.car.userData.gas):100;H.mission.textContent=missions.find(x=>x.id===S.mission)?.name||'None';H.pos.textContent=[S.p.x,S.p.y,S.p.z].map(Math.round).join(',');H.chunks.textContent=S.chunks.size;H.npcs.textContent=0;H.active.textContent=S.car?'yes':'none';H.slot.textContent=S.slot;}
let frames=0,ft=0;function loop(){let dt=Math.min(clock.getDelta(),.05);frames++;ft+=dt;if(ft>1){H.fps.textContent=frames;frames=0;ft=0;}step(dt);renderer.render(scene,camera);requestAnimationFrame(loop);}
function map(){if(!mini)return;mini.clearRect(0,0,160,160);mini.fillStyle='#050814';mini.fillRect(0,0,160,160);mini.strokeStyle='#17f3ff55';for(let i=0;i<160;i+=20){mini.beginPath();mini.moveTo(i,0);mini.lineTo(i,160);mini.moveTo(0,i);mini.lineTo(160,i);mini.stroke();}function dot(x,z,c,s){mini.fillStyle=c;mini.fillRect(80+(x-S.p.x)/3-s/2,80+(z-S.p.z)/3-s/2,s,s);}S.cars.forEach(c=>dot(c.position.x,c.position.z,'#ff3366',5));S.pickups.slice(0,60).forEach(p=>dot(p.position.x,p.position.z,'#17f3ff',3));dot(S.p.x,S.p.z,'#5ef38c',7);}
function snap(){return{cash:S.cash,xp:S.xp,level:S.level,wanted:S.wanted,owned:S.owned,got:S.got,p:{x:S.p.x,y:S.p.y,z:S.p.z},mission:S.mission,prog};}
async function save(slot='slot1',note){S.slot=slot;S.last=Date.now();let b=window.NeonBlockSaveBackend;if(b)await b.save(slot,snap());else localStorage.setItem('neonblock-city:'+slot,JSON.stringify(snap()));if(note)toast('Saved '+slot);}
async function load(slot='slot1',note){S.slot=slot;let b=window.NeonBlockSaveBackend,d=b?await b.load(slot):JSON.parse(localStorage.getItem('neonblock-city:'+slot)||'null');if(d&&d.p){Object.assign(S,{cash:d.cash??S.cash,xp:d.xp??0,level:d.level??1,wanted:d.wanted??0,owned:d.owned||{},got:d.got||{},mission:d.mission||null});Object.assign(prog,d.prog||{});Object.assign(S.p,d.p);if(note)toast('Loaded '+slot);}}
function exportSave(){let b=$('export-json');if(b)b.value=JSON.stringify(snap(),null,2);}
function importSave(){try{let d=JSON.parse($('export-json').value);Object.assign(S,{cash:d.cash??S.cash,xp:d.xp??S.xp,owned:d.owned||S.owned,got:d.got||S.got,mission:d.mission||null});if(d.p)Object.assign(S.p,d.p);toast('Imported save');}catch(e){toast('Import failed');}}
function show(id){$(id)?.classList.remove('hidden');$('pause-overlay')?.classList.remove('hidden');}
function hide(id){$(id)?.classList.add('hidden');}
function pause(){$('pause-overlay')?.classList.toggle('hidden');}
function toast(t){toastBox.textContent=t;toastBox.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>toastBox.classList.add('hidden'),1600);}
function reward(t,c,x){toast(t+' +$'+c+' +'+x+'XP');}
boot();
})();
