/* NeonBlock City - static playable browser game */
(function(){
'use strict';
const $=(id)=>document.getElementById(id);
const canvas=$('game-canvas');
const loading=$('loading-screen');
const hud={cash:$('hud-cash'),xp:$('hud-xp'),level:$('hud-level'),wanted:$('hud-wanted'),online:$('hud-online'),vehicle:$('hud-vehicle'),hp:$('hud-vehicle-hp'),gas:$('hud-vehicle-gas'),mission:$('hud-mission'),fps:$('debug-fps'),pos:$('debug-pos'),chunks:$('debug-chunks'),npcs:$('debug-npcs'),activeVehicle:$('debug-active-vehicle'),saveSlot:$('debug-save-slot'),debugOnline:$('debug-online'),err:$('debug-last-error')};
const debug=$('debug-overlay');
const minimap=$('minimap-canvas');
const mctx=minimap.getContext('2d');
const qualitySel=$('graphics-quality');
const reward=$('reward-popup');
const isTouch=('ontouchstart' in window)||navigator.maxTouchPoints>0;
let renderer,scene,camera,clock; let last=performance.now(),fps=60,paused=false,debugOn=false,quality='auto';
const state={cash:120,xp:0,level:1,wanted:0,slot:'slot1',spawn:{x:0,z:0},owned:{},collected:{},mission:null,missionsDone:{},cloud:'offline'};
const player={mesh:null,pos:new THREE.Vector3(0,1.1,0),vel:new THREE.Vector3(),yaw:0,onGround:false,sprint:false,vehicle:null,hp:100};
const keys={}; const input={mx:0,mz:0,jump:false,interact:false,lookX:0,lookY:0};
const chunks=new Map(),colliders=[],vehicles=[],pickups=[],npcs=[],lots=[]; const CHUNK=64,VIEW=2;
const missions=[
{id:'courier',name:'Courier Sprint',desc:'Collect 4 neon cubes before the timer ends.',goal:4,reward:180,xp:60,type:'collect'},
{id:'garage',name:'Garage Check',desc:'Enter a vehicle, drive to the blue marker, then exit.',goal:1,reward:260,xp:80,type:'drive'},
{id:'owner',name:'First Property',desc:'Buy one city lot to start your empire.',goal:1,reward:350,xp:90,type:'own'}
];
const store={key:'neonblock-city-save-v24',save(){const payload={state,player:{x:player.pos.x,y:player.pos.y,z:player.pos.z,yaw:player.yaw,hp:player.hp}};localStorage.setItem(this.key+':'+state.slot,JSON.stringify(payload)); window.NeonBlockCloud?.save?.(state.slot,payload).catch(()=>{});},load(slot=state.slot){const raw=localStorage.getItem(this.key+':'+slot); if(!raw)return false; const data=JSON.parse(raw); Object.assign(state,data.state||{}); if(data.player){player.pos.set(data.player.x||0,data.player.y||1.1,data.player.z||0);player.yaw=data.player.yaw||0;player.hp=data.player.hp||100;} applyPersistence(); return true;}};
function init(){
 if(!window.THREE) throw new Error('Three.js failed to load');
 renderer=new THREE.WebGLRenderer({canvas,antialias:!isTouch,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,isTouch?1.5:2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=!isTouch;
 scene=new THREE.Scene(); scene.background=new THREE.Color(0x050814); scene.fog=new THREE.Fog(0x050814,70,230);
 camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,0.1,550);
 clock=new THREE.Clock();
 scene.add(new THREE.HemisphereLight(0x66ccff,0x110022,1.8)); const sun=new THREE.DirectionalLight(0xffffff,1.7); sun.position.set(30,60,20); sun.castShadow=!isTouch; scene.add(sun);
 const grid=new THREE.GridHelper(512,64,0x17f3ff,0x1b244d); grid.material.opacity=.17; grid.material.transparent=true; scene.add(grid);
 player.mesh=createAvatar(); scene.add(player.mesh);
 setupControls(); setupMenu(); updateChunks(true); applyPersistence(); if(!store.load('slot1')) store.save(); updateHud(); loading?.classList.add('hidden'); requestAnimationFrame(loop);
}
function createAvatar(){const g=new THREE.Group(); const mat=new THREE.MeshStandardMaterial({color:0x28d7ff,emissive:0x082044,roughness:.55}); const body=new THREE.Mesh(new THREE.BoxGeometry(.8,1.2,.45),mat); body.position.y=.55; g.add(body); const head=new THREE.Mesh(new THREE.BoxGeometry(.55,.55,.55),new THREE.MeshStandardMaterial({color:0xffd15c,roughness:.6})); head.position.y=1.45; g.add(head); const visor=new THREE.Mesh(new THREE.BoxGeometry(.5,.12,.04),new THREE.MeshBasicMaterial({color:0x111827})); visor.position.set(0,1.5,-.3); g.add(visor); return g;}
function makeBuilding(x,z,w,d,h,color){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.07,roughness:.85})); m.position.set(x,h/2,z); m.castShadow=m.receiveShadow=!isTouch; scene.add(m); colliders.push({x:x-w/2,z:z-d/2,w,d,mesh:m}); return m;}
function makePickup(x,z,id){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.7),new THREE.MeshStandardMaterial({color:0x5ef38c,emissive:0x30ff86,emissiveIntensity:.8})); m.position.set(x,1,z); m.userData={id,type:'pickup'}; scene.add(m); pickups.push(m); return m;}
function makeVehicle(x,z,id){const g=new THREE.Group(); const body=new THREE.Mesh(new THREE.BoxGeometry(2.7,.7,4.2),new THREE.MeshStandardMaterial({color:0xff2aa1,emissive:0x330018,roughness:.45})); body.position.y=.55; g.add(body); const top=new THREE.Mesh(new THREE.BoxGeometry(1.6,.55,1.8),new THREE.MeshStandardMaterial({color:0x141a3b,roughness:.35})); top.position.y=1.15; g.add(top); for(const sx of[-1,1])for(const sz of[-1.25,1.25]){const wh=new THREE.Mesh(new THREE.CylinderGeometry(.35,.35,.25,12),new THREE.MeshStandardMaterial({color:0x111111})); wh.rotation.z=Math.PI/2; wh.position.set(sx*1.35,.28,sz); g.add(wh);} g.position.set(x,0,z); g.userData={id,type:'vehicle',hp:100,gas:100,owned:false,speed:0}; scene.add(g); vehicles.push(g); return g;}
function makeNpc(x,z,id){const m=new THREE.Mesh(new THREE.BoxGeometry(.65,1.55,.65),new THREE.MeshStandardMaterial({color:0xfacc15,emissive:0x221400})); m.position.set(x,.8,z); m.userData={id,base:new THREE.Vector3(x,.8,z),t:Math.random()*99}; scene.add(m); npcs.push(m);}
function makeLot(x,z,id,price){const m=new THREE.Mesh(new THREE.BoxGeometry(8,.08,8),new THREE.MeshBasicMaterial({color:0x17f3ff,transparent:true,opacity:.25})); m.position.set(x,.04,z); m.userData={id,price,type:'lot'}; scene.add(m); lots.push(m);}
function updateChunks(force=false){const cx=Math.floor(player.pos.x/CHUNK),cz=Math.floor(player.pos.z/CHUNK); for(let x=cx-VIEW;x<=cx+VIEW;x++)for(let z=cz-VIEW;z<=cz+VIEW;z++){const key=x+','+z;if(!chunks.has(key)) buildChunk(x,z,key);} for(const [key,obj]of chunks){const [x,z]=key.split(',').map(Number); if(Math.abs(x-cx)>VIEW+1||Math.abs(z-cz)>VIEW+1){obj.items.forEach(o=>scene.remove(o)); chunks.delete(key);}}
}
function buildChunk(cx,cz,key){const items=[]; const baseX=cx*CHUNK,baseZ=cz*CHUNK; const roadMat=new THREE.MeshStandardMaterial({color:0x11172e,roughness:.9}); for(let i=0;i<2;i++){const road=new THREE.Mesh(new THREE.BoxGeometry(i?8:CHUNK,.04,i?CHUNK:8),roadMat); road.position.set(baseX+CHUNK/2,.02,baseZ+CHUNK/2); scene.add(road); items.push(road);} const rng=Math.abs(Math.sin(cx*928.17+cz*133.7)); for(let i=0;i<7;i++){const x=baseX+10+((i*17+cx*11)%45), z=baseZ+10+((i*23+cz*9)%45); if(Math.abs((x%CHUNK)-CHUNK/2)<8||Math.abs((z%CHUNK)-CHUNK/2)<8)continue; items.push(makeBuilding(x,z,6+((i+cx)&3)*2,6+((i+cz)&2)*2,8+(((i+1)*7+rng*10)%32),[0x263bff,0x8b5cf6,0x00d4ff,0xff2aa1][i%4]));}
 if((cx+cz)%2===0)items.push(makePickup(baseX+18,baseZ+48,'p'+key)); if((cx-cz)%3===0)items.push(makeVehicle(baseX+46,baseZ+18,'v'+key)); if((cx+cz)%4===0)items.push(makeNpc(baseX+30,baseZ+34,'n'+key)); if((cx*cz)%5===0)items.push(makeLot(baseX+50,baseZ+50,'lot'+key,300+Math.abs(cx+cz)*35)); chunks.set(key,{items});}
function setupControls(){addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Escape')togglePause();if(e.code==='F3'){debugOn=!debugOn;debug.classList.toggle('hidden',!debugOn)}}); addEventListener('keyup',e=>keys[e.code]=false); addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}); canvas.addEventListener('pointerdown',e=>canvas.setPointerCapture(e.pointerId)); canvas.addEventListener('pointermove',e=>{if(e.buttons&&e.clientX>innerWidth*.35){player.yaw-=e.movementX*.004; input.lookY=Math.max(-.8,Math.min(.8,input.lookY-e.movementY*.002));}});
 const joy=$('joystick-container'),stick=$('joystick-stick'); let jid=null; joy?.addEventListener('pointerdown',e=>{jid=e.pointerId; joy.setPointerCapture(jid); setJoy(e);}); joy?.addEventListener('pointermove',e=>{if(e.pointerId===jid)setJoy(e)}); joy?.addEventListener('pointerup',()=>{jid=null;input.mx=input.mz=0;stick.style.transform='translate(0,0)'}); function setJoy(e){const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),d=Math.min(42,Math.hypot(dx,dy)),a=Math.atan2(dy,dx); input.mx=Math.cos(a)*d/42; input.mz=Math.sin(a)*d/42; stick.style.transform=`translate(${Math.cos(a)*d}px,${Math.sin(a)*d}px)`;}
 bindBtn('btn-mobile-jump',()=>input.jump=true); bindBtn('btn-mobile-sprint',()=>player.sprint=!player.sprint); bindBtn('btn-mobile-interact',()=>interact()); bindBtn('btn-mobile-unstuck',()=>unstuck()); bindBtn('btn-mobile-pause',()=>togglePause());}
function bindBtn(id,fn){const b=$(id); if(b)b.addEventListener('click',fn)}
function setupMenu(){bindBtn('btn-resume',()=>togglePause(false));bindBtn('btn-settings',()=>$('settings-panel').classList.toggle('hidden'));bindBtn('btn-save',()=>{$('save-panel').classList.remove('hidden')});bindBtn('btn-load',()=>{$('save-panel').classList.remove('hidden')});bindBtn('btn-close-settings',()=>$('settings-panel').classList.add('hidden'));bindBtn('btn-close-save',()=>$('save-panel').classList.add('hidden'));document.querySelectorAll('.btn-save-slot').forEach(b=>b.onclick=()=>{state.slot=b.dataset.slot;store.save();pop('Saved '+state.slot)});document.querySelectorAll('.btn-load-slot').forEach(b=>b.onclick=()=>{state.slot=b.dataset.slot;pop(store.load(state.slot)?'Loaded '+state.slot:'No save in '+state.slot)});bindBtn('btn-export',()=>{$('export-json').value=localStorage.getItem(store.key+':'+state.slot)||''});bindBtn('btn-import',()=>{try{localStorage.setItem(store.key+':'+state.slot,$('export-json').value);store.load(state.slot);pop('Imported save')}catch(e){setErr(e)}}); qualitySel?.addEventListener('change',()=>setQuality(qualitySel.value));}
function togglePause(v=!paused){paused=v;$('pause-overlay').classList.toggle('hidden',!paused)}
function loop(t){requestAnimationFrame(loop); const dt=Math.min(.05,clock.getDelta()); fps=fps*.9+(1/dt)*.1; if(!paused)update(dt,t); render();}
function update(dt,t){input.jump=keys.Space||input.jump; player.sprint=keys.ShiftLeft||keys.ShiftRight||player.sprint; const ax=(keys.KeyD?1:0)-(keys.KeyA?1:0)+input.mx; const az=(keys.KeyS?1:0)-(keys.KeyW?1:0)+input.mz; if(keys.KeyE)interact(); if(keys.KeyR)unstuck(); if(keys.KeyM)startNextMission();
 if(player.vehicle)updateVehicle(dt,ax,az); else updatePlayer(dt,ax,az); updateChunks(); updatePickups(); updateNpcs(t*.001); updateMission(dt); updateCamera(dt); updateHud(); drawMinimap(); if(t-last>8000){last=t;store.save();}}
function updatePlayer(dt,ax,az){const speed=player.sprint?9:5.2; const fwd=new THREE.Vector3(Math.sin(player.yaw),0,Math.cos(player.yaw)); const right=new THREE.Vector3(fwd.z,0,-fwd.x); const move=fwd.multiplyScalar(-az).add(right.multiplyScalar(ax)); if(move.lengthSq()>1)move.normalize(); player.vel.x=move.x*speed; player.vel.z=move.z*speed; player.vel.y-=22*dt; if(input.jump&&player.onGround){player.vel.y=8;player.onGround=false} input.jump=false; player.pos.addScaledVector(player.vel,dt); if(player.pos.y<1.1){player.pos.y=1.1;player.vel.y=0;player.onGround=true} resolveCollisions(.5); player.mesh.position.copy(player.pos); player.mesh.rotation.y=player.yaw;}
function updateVehicle(dt,ax,az){const v=player.vehicle,ud=v.userData; ud.speed+=( -az*18 - ud.speed*2.5)*dt; ud.speed=Math.max(-10,Math.min(22,ud.speed)); v.rotation.y-=ax*dt*(Math.abs(ud.speed)*.045+.8); const dir=new THREE.Vector3(Math.sin(v.rotation.y),0,Math.cos(v.rotation.y)); v.position.addScaledVector(dir,ud.speed*dt); ud.gas=Math.max(0,ud.gas-Math.abs(ud.speed)*dt*.035); player.pos.copy(v.position).add(new THREE.Vector3(0,1.3,0)); player.mesh.visible=false; if(keys.KeyQ||ud.gas<=0){player.vehicle=null;player.mesh.visible=true;player.pos.add(new THREE.Vector3(2,0,0));pop(ud.gas<=0?'Out of gas':'Exited vehicle')}}
function resolveCollisions(r){for(const c of colliders){if(player.pos.x>c.x-r&&player.pos.x<c.x+c.w+r&&player.pos.z>c.z-r&&player.pos.z<c.z+c.d+r){const left=Math.abs(player.pos.x-c.x),right=Math.abs(c.x+c.w-player.pos.x),top=Math.abs(player.pos.z-c.z),bot=Math.abs(c.z+c.d-player.pos.z); const m=Math.min(left,right,top,bot); if(m===left)player.pos.x=c.x-r; else if(m===right)player.pos.x=c.x+c.w+r; else if(m===top)player.pos.z=c.z-r; else player.pos.z=c.z+c.d+r;}}}
function interact(){let near=null,dist=999; [...vehicles,...lots].forEach(o=>{const d=o.position.distanceTo(player.pos); if(d<dist){dist=d;near=o}}); if(!near||dist>5){startNextMission();return} if(near.userData.type==='vehicle'){player.vehicle=near; near.userData.owned=true; pop('Vehicle entered. Q exits.'); if(state.mission?.type==='drive')finishMission();} else if(near.userData.type==='lot'){const id=near.userData.id;if(state.owned[id]){pop('Already owned lot')}else if(state.cash>=near.userData.price){state.cash-=near.userData.price;state.owned[id]=true;near.material.color.set(0x5ef38c);pop('Bought lot: $'+near.userData.price); if(state.mission?.type==='own')finishMission();}else pop('Need $'+near.userData.price)}}
function updatePickups(){for(const p of pickups){p.rotation.y+=.03;if(state.collected[p.userData.id]){p.visible=false;continue} if(p.position.distanceTo(player.pos)<2){state.collected[p.userData.id]=true;p.visible=false;state.cash+=25;state.xp+=8;pop('Picked neon cube +$25'); if(state.mission?.type==='collect'){state.mission.progress++; if(state.mission.progress>=state.mission.goal)finishMission();}}}}
function updateNpcs(t){for(const n of npcs){n.userData.t+=.01;n.position.x=n.userData.base.x+Math.sin(t+n.userData.t)*2;n.position.z=n.userData.base.z+Math.cos(t*.7+n.userData.t)*2;}}
function startNextMission(){if(state.mission)return; const m=missions.find(x=>!state.missionsDone[x.id])||missions[0]; state.mission={...m,progress:0,time:180}; pop('Mission started: '+m.name)}
function updateMission(dt){if(!state.mission)return; state.mission.time-=dt; if(state.mission.time<=0){pop('Mission failed: '+state.mission.name);state.mission=null;}}
function finishMission(){const m=state.mission;if(!m)return;state.cash+=m.reward;state.xp+=m.xp;state.missionsDone[m.id]=true;state.mission=null;pop('Mission complete +$'+m.reward+' +'+m.xp+'XP');store.save();}
function applyPersistence(){lots.forEach(l=>{if(state.owned[l.userData.id])l.material.color.set(0x5ef38c)}); pickups.forEach(p=>{if(state.collected[p.userData.id])p.visible=false});}
function updateCamera(dt){const target=player.vehicle?player.vehicle.position:player.pos; const back=new THREE.Vector3(Math.sin(player.yaw),.35,Math.cos(player.yaw)).multiplyScalar(10); const want=target.clone().add(back).add(new THREE.Vector3(0,5+input.lookY*3,0)); camera.position.lerp(want,1-Math.pow(.001,dt)); camera.lookAt(target.x,target.y+1.2,target.z);}
function updateHud(){state.level=Math.max(1,Math.floor(state.xp/100)+1); hud.cash.textContent='$'+state.cash;hud.xp.textContent=state.xp;hud.level.textContent=state.level;hud.wanted.textContent=state.wanted;hud.online.textContent=state.cloud;hud.debugOnline.textContent=state.cloud;hud.vehicle.textContent=player.vehicle?'Neon Cruiser':'On foot';hud.hp.textContent=player.vehicle?Math.round(player.vehicle.userData.hp):player.hp;hud.gas.textContent=player.vehicle?Math.round(player.vehicle.userData.gas):'--';hud.mission.textContent=state.mission?`${state.mission.name} ${state.mission.progress}/${state.mission.goal}`:'None';hud.fps.textContent=Math.round(fps);hud.pos.textContent=`${player.pos.x.toFixed(1)},${player.pos.y.toFixed(1)},${player.pos.z.toFixed(1)}`;hud.chunks.textContent=chunks.size;hud.npcs.textContent=npcs.length;hud.activeVehicle.textContent=player.vehicle?player.vehicle.userData.id:'None';hud.saveSlot.textContent=state.slot;}
function drawMinimap(){mctx.clearRect(0,0,160,160);mctx.fillStyle='#050814';mctx.fillRect(0,0,160,160);mctx.strokeStyle='#17f3ff55';for(let i=0;i<160;i+=20){mctx.beginPath();mctx.moveTo(i,0);mctx.lineTo(i,160);mctx.moveTo(0,i);mctx.lineTo(160,i);mctx.stroke()} const scale=1.2; const plot=(x,z,c,s=3)=>{mctx.fillStyle=c;mctx.fillRect(80+(x-player.pos.x)/scale-s/2,80+(z-player.pos.z)/scale-s/2,s,s)}; lots.forEach(l=>state.owned[l.userData.id]&&plot(l.position.x,l.position.z,'#5ef38c',5)); vehicles.forEach(v=>plot(v.position.x,v.position.z,'#ff2aa1',4)); pickups.forEach(p=>p.visible&&plot(p.position.x,p.position.z,'#facc15',3)); plot(player.pos.x,player.pos.z,'#17f3ff',7);}
function render(){renderer.render(scene,camera)}
function setQuality(q){quality=q; const low=q==='low'||(q==='auto'&&isTouch); renderer.setPixelRatio(low?1:Math.min(devicePixelRatio,2)); scene.fog.far=low?170:260; pop('Graphics: '+q)}
function unstuck(){player.vehicle=null;player.mesh.visible=true;player.pos.set(state.spawn.x,1.1,state.spawn.z);player.vel.set(0,0,0);pop('Unstuck to spawn')}
function pop(msg){reward.textContent=msg;reward.classList.remove('hidden');clearTimeout(pop.t);pop.t=setTimeout(()=>reward.classList.add('hidden'),1800)}
function setErr(e){console.error(e);hud.err.textContent=e.message||String(e);pop('Error: '+(e.message||e))}
addEventListener('visibilitychange',()=>{if(document.hidden)store.save()}); addEventListener('beforeunload',()=>store.save());
try{init()}catch(e){setErr(e); if(loading)loading.querySelector('.loading-sub').textContent='Boot error: '+e.message;}
})();
