/* NeonBlock City - static playable runtime */
(function(){
'use strict';
const $=(id)=>document.getElementById(id);
const canvas=$('game-canvas');
const hasTHREE=typeof THREE!=='undefined';
const state={cash:250,xp:0,level:1,wanted:0,hp:100,gas:100,slot:'slot1',online:'offline',mission:null,owned:new Set(),crates:new Set(),vehicle:null,pos:{x:0,y:1.1,z:0},vel:{x:0,y:0,z:0},keys:{},joy:{x:0,y:0},chunks:new Map(),npcs:[],vehicles:[],lots:[],lastSave:0,lastError:'none'};
const missions=[{id:'courier',name:'Neon Courier',text:'Collect 3 glowing crates',target:3,reward:350,xp:90,type:'crate'},{id:'driver',name:'Test Drive',text:'Enter a hover car and drive 250m',target:250,reward:500,xp:120,type:'drive'},{id:'owner',name:'First Lot',text:'Buy one city lot',target:1,reward:250,xp:150,type:'own'}];
const ui={cash:$('hud-cash'),xp:$('hud-xp'),level:$('hud-level'),wanted:$('hud-wanted'),online:$('hud-online'),vehicle:$('hud-vehicle'),vhp:$('hud-vehicle-hp'),gas:$('hud-vehicle-gas'),mission:$('hud-mission'),fps:$('debug-fps'),pos:$('debug-pos'),chunks:$('debug-chunks'),npcs:$('debug-npcs'),active:$('debug-active-vehicle'),slot:$('debug-save-slot'),dbgOnline:$('debug-online'),err:$('debug-last-error'),reward:$('reward-popup'),pause:$('pause-overlay'),savePanel:$('save-panel'),settings:$('settings-panel'),missionBoard:$('mission-board'),missionList:$('mission-list'),loading:$('loading-screen'),mini:$('minimap-canvas')};
let scene,camera,renderer,player,clock,lastT=performance.now(),frames=0,dist=0,quality='auto';
function setText(el,v){ if(el) el.textContent=String(v); }
function toast(t){ if(!ui.reward)return; ui.reward.textContent=t; ui.reward.classList.remove('hidden'); clearTimeout(toast.t); toast.t=setTimeout(()=>ui.reward.classList.add('hidden'),1800); }
function savePayload(){return {v:2,cash:state.cash,xp:state.xp,level:state.level,wanted:state.wanted,pos:state.pos,owned:[...state.owned],crates:[...state.crates],mission:state.mission,vehicle:!!state.vehicle,gas:state.gas};}
async function save(slot=state.slot){state.slot=slot; const data=savePayload(); localStorage.setItem('neonblock:'+slot,JSON.stringify(data)); if(window.NeonBlockCloud?.save){try{await window.NeonBlockCloud.save(slot,data);state.online='cloud saved';}catch(e){state.online='local save';state.lastError=e.message||'cloud save failed';}} toast('Saved '+slot); updateHud();}
async function load(slot=state.slot){const raw=localStorage.getItem('neonblock:'+slot); if(!raw){toast('No save in '+slot);return;} try{const d=JSON.parse(raw); state.cash=d.cash??250;state.xp=d.xp??0;state.level=d.level??1;state.wanted=d.wanted??0;state.pos=d.pos||state.pos;state.owned=new Set(d.owned||[]);state.crates=new Set(d.crates||[]);state.mission=d.mission||null;state.gas=d.gas??100; if(player) player.position.set(state.pos.x,1.1,state.pos.z); toast('Loaded '+slot);}catch(e){state.lastError=e.message;} updateHud();}
function completeMission(){const m=missions.find(x=>x.id===state.mission?.id); if(!m)return; state.cash+=m.reward; state.xp+=m.xp; state.level=1+Math.floor(state.xp/200); toast('Mission complete: +$'+m.reward); state.mission=null;}
function progress(type,amt=1){if(!state.mission)return; const m=missions.find(x=>x.id===state.mission.id); if(!m||m.type!==type)return; state.mission.progress=Math.min(m.target,(state.mission.progress||0)+amt); if(state.mission.progress>=m.target) completeMission();}
function updateHud(){setText(ui.cash,'$'+state.cash);setText(ui.xp,state.xp);setText(ui.level,state.level);setText(ui.wanted,state.wanted);setText(ui.online,state.online);setText(ui.vehicle,state.vehicle?'Hover Car':'On foot');setText(ui.vhp,state.hp);setText(ui.gas,Math.round(state.gas));setText(ui.mission,state.mission?state.mission.name+' '+(state.mission.progress||0)+'/'+missions.find(m=>m.id===state.mission.id).target:'None');setText(ui.chunks,state.chunks.size);setText(ui.npcs,state.npcs.length);setText(ui.active,state.vehicle?'car':'none');setText(ui.slot,state.slot);setText(ui.dbgOnline,state.online);setText(ui.err,state.lastError); if(player)setText(ui.pos,`${player.position.x.toFixed(1)},${player.position.y.toFixed(1)},${player.position.z.toFixed(1)}`);}
function makeMat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.75,metalness:.15});}
function init3d(){scene=new THREE.Scene();scene.background=new THREE.Color(0x070b18);scene.fog=new THREE.Fog(0x070b18,45,170);camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,500);renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;clock=new THREE.Clock();scene.add(new THREE.HemisphereLight(0x8adfff,0x15182e,1.8));const sun=new THREE.DirectionalLight(0xffffff,1.4);sun.position.set(30,60,20);sun.castShadow=true;scene.add(sun);const g=new THREE.BoxGeometry(.9,1.8,.9);player=new THREE.Mesh(g,makeMat(0x17f3ff));player.position.set(state.pos.x,1.1,state.pos.z);player.castShadow=true;scene.add(player);camera.position.set(0,10,14);makeWorldAround();}
function chunkKey(cx,cz){return cx+','+cz}
function makeWorldAround(){if(!scene)return;const cx=Math.floor(player.position.x/32),cz=Math.floor(player.position.z/32);for(let x=cx-2;x<=cx+2;x++)for(let z=cz-2;z<=cz+2;z++)makeChunk(x,z);for(const [k,o] of state.chunks){const [x,z]=k.split(',').map(Number);if(Math.abs(x-cx)>3||Math.abs(z-cz)>3){scene.remove(o.group);state.chunks.delete(k);}}
}
function makeChunk(cx,cz){const k=chunkKey(cx,cz);if(state.chunks.has(k))return;const group=new THREE.Group();group.position.set(cx*32,0,cz*32);const road= new THREE.Mesh(new THREE.BoxGeometry(32,.08,32),makeMat((cx+cz)%2?0x10162f:0x0d1228));road.receiveShadow=true;group.add(road);for(let i=0;i<8;i++){const bx=((i*7+cx*11)%28)-14,bz=((i*5+cz*13)%28)-14,h=4+Math.abs((cx*cz+i)%10);const b=new THREE.Mesh(new THREE.BoxGeometry(4,h,4),makeMat(i%3?0x26346c:0x361b66));b.position.set(bx,h/2,bz);b.castShadow=true;group.add(b);} if((cx+cz)%2===0){const crate=new THREE.Mesh(new THREE.BoxGeometry(1.2,1.2,1.2),makeMat(0xffd447));crate.name='crate:'+k;crate.position.set(10,1,-8);group.add(crate);} if(cx%2===0&&cz%2!==0){const lot=new THREE.Mesh(new THREE.BoxGeometry(7,.12,7),makeMat(0x23ff7a));lot.name='lot:'+k;lot.position.set(-9,.15,9);group.add(lot);state.lots.push(lot);} if((cx-cz)%3===0){const car=new THREE.Mesh(new THREE.BoxGeometry(2.2,1,3.8),makeMat(0xff3377));car.name='car';car.position.set(7,.7,7);group.add(car);state.vehicles.push(car);} if((cx+cz)%3===1){const npc=new THREE.Mesh(new THREE.BoxGeometry(.8,1.6,.8),makeMat(0xffffff));npc.position.set(-6,.9,-6);group.add(npc);state.npcs.push(npc);} scene.add(group);state.chunks.set(k,{group});}
function interact(){if(!player)return; const p=player.position; for(const c of state.vehicles){const wp=c.getWorldPosition(new THREE.Vector3()); if(wp.distanceTo(p)<3){state.vehicle=state.vehicle?null:c;toast(state.vehicle?'Vehicle entered':'Vehicle exited');return;}} for(const l of state.lots){const wp=l.getWorldPosition(new THREE.Vector3()); if(wp.distanceTo(p)<4){const id=l.name; if(!state.owned.has(id)){const price=300;if(state.cash>=price){state.cash-=price;state.owned.add(id);progress('own');toast('Lot bought');}else toast('Need $300');}return;}} scene.traverse(o=>{if(!o.name?.startsWith('crate:')||state.crates.has(o.name))return;const wp=o.getWorldPosition(new THREE.Vector3());if(wp.distanceTo(p)<2.5){state.crates.add(o.name);o.visible=false;state.cash+=50;state.xp+=20;progress('crate');toast('Crate collected');}}); updateHud();}
function move(dt){const speed=(state.vehicle?13:6)*(state.keys.ShiftLeft||state.keys.ShiftRight?1.55:1);let x=state.joy.x,z=state.joy.y;if(state.keys.KeyW||state.keys.ArrowUp)z-=1;if(state.keys.KeyS||state.keys.ArrowDown)z+=1;if(state.keys.KeyA||state.keys.ArrowLeft)x-=1;if(state.keys.KeyD||state.keys.ArrowRight)x+=1;const len=Math.hypot(x,z)||1;const dx=x/len*speed*dt,dz=z/len*speed*dt;player.position.x+=dx;player.position.z+=dz;if(state.vehicle){state.gas=Math.max(0,state.gas-(Math.abs(dx)+Math.abs(dz))*.08);dist+=(Math.abs(dx)+Math.abs(dz));progress('drive',Math.abs(dx)+Math.abs(dz));}state.pos={x:player.position.x,y:1.1,z:player.position.z};camera.position.lerp(new THREE.Vector3(player.position.x,10,player.position.z+14),.08);camera.lookAt(player.position);makeWorldAround();}
function drawMini(){const m=ui.mini;if(!m)return;const ctx=m.getContext('2d');ctx.clearRect(0,0,160,160);ctx.fillStyle='#050814cc';ctx.fillRect(0,0,160,160);ctx.fillStyle='#17f3ff';ctx.fillRect(78,78,4,4);ctx.strokeStyle='#17f3ff55';for(let i=0;i<160;i+=20){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,160);ctx.moveTo(0,i);ctx.lineTo(160,i);ctx.stroke();}}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);move(dt);renderer.render(scene,camera);drawMini();frames++;const now=performance.now();if(now-lastT>1000){setText(ui.fps,frames);frames=0;lastT=now;} if(now-state.lastSave>30000){state.lastSave=now;save(state.slot);}updateHud();}
function bind(){addEventListener('keydown',e=>{state.keys[e.code]=true;if(e.code==='KeyE')interact();if(e.code==='Escape')ui.pause?.classList.toggle('hidden');if(e.code==='KeyM')openMissions();});addEventListener('keyup',e=>state.keys[e.code]=false);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});$('btn-resume')?.addEventListener('click',()=>ui.pause.classList.add('hidden'));$('btn-settings')?.addEventListener('click',()=>ui.settings.classList.toggle('hidden'));$('btn-save')?.addEventListener('click',()=>ui.savePanel.classList.remove('hidden'));$('btn-load')?.addEventListener('click',()=>load(state.slot));$('btn-close-save')?.addEventListener('click',()=>ui.savePanel.classList.add('hidden'));$('btn-close-settings')?.addEventListener('click',()=>ui.settings.classList.add('hidden'));$('graphics-quality')?.addEventListener('change',e=>{quality=e.target.value;renderer.setPixelRatio(quality==='low'?1:Math.min(devicePixelRatio,quality==='high'?2:1.5));});document.querySelectorAll('.btn-save-slot').forEach(b=>b.addEventListener('click',()=>save(b.dataset.slot)));document.querySelectorAll('.btn-load-slot').forEach(b=>b.addEventListener('click',()=>load(b.dataset.slot)));$('btn-export')?.addEventListener('click',()=>{$('export-json').value=JSON.stringify(savePayload());});$('btn-import')?.addEventListener('click',()=>{try{localStorage.setItem('neonblock:'+state.slot,$('export-json').value);load(state.slot);}catch(e){state.lastError=e.message;}});$('btn-mobile-interact')?.addEventListener('click',interact);$('btn-mobile-jump')?.addEventListener('click',()=>toast('Jump!'));$('btn-mobile-pause')?.addEventListener('click',()=>ui.pause.classList.toggle('hidden'));$('btn-mobile-unstuck')?.addEventListener('click',()=>{player.position.set(0,1.1,0);});$('btn-mobile-sprint')?.addEventListener('pointerdown',()=>state.keys.ShiftLeft=true);$('btn-mobile-sprint')?.addEventListener('pointerup',()=>state.keys.ShiftLeft=false);const jc=$('joystick-container'),st=$('joystick-stick');let active=false;function joy(e){const r=jc.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;const p=e.touches?e.touches[0]:e;let x=(p.clientX-cx)/(r.width/2),y=(p.clientY-cy)/(r.height/2);const l=Math.max(1,Math.hypot(x,y));x/=l;y/=l;state.joy={x,y};if(st){st.style.transform=`translate(${x*34}px,${y*34}px)`;}}jc?.addEventListener('pointerdown',e=>{active=true;jc.setPointerCapture(e.pointerId);joy(e);});jc?.addEventListener('pointermove',e=>{if(active)joy(e);});jc?.addEventListener('pointerup',()=>{active=false;state.joy={x:0,y:0};if(st)st.style.transform='';});}
function openMissions(){if(!ui.missionList)return;ui.missionList.innerHTML='';missions.forEach(m=>{const li=document.createElement('li');const b=document.createElement('button');b.textContent=m.name+' - '+m.text;b.onclick=()=>{state.mission={id:m.id,name:m.name,progress:0};ui.missionBoard.classList.add('hidden');toast('Mission started');};li.appendChild(b);ui.missionList.appendChild(li);});ui.missionBoard.classList.remove('hidden');}
function fallback(){document.body.innerHTML='<main class="menu-card" style="margin:4rem auto"><h1>NeonBlock City</h1><p>Three.js failed to load. Check connection, then refresh.</p></main>';}
function start(){try{if(!hasTHREE)return fallback();init3d();bind();load('slot1').catch(()=>{});ui.loading?.remove();loop();toast('WASD/Arrows move • E interact • M missions');}catch(e){state.lastError=e.message;console.error(e);fallback();}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
