function bindViewEvents(){
 $$('.holding[data-card-id]').forEach(el=>el.addEventListener('click',()=>openCardDialog(state.holdings.find(h=>h.id===el.dataset.cardId))));
 $('#portfolioAdd')?.addEventListener('click',()=>openCardDialog());
 $('#portfolioSearch')?.addEventListener('input',e=>{state.filter.q=e.target.value;render()});
 $('#categoryFilter')?.addEventListener('change',e=>{state.filter.category=e.target.value;render()});
 $('#pricingFilter')?.addEventListener('change',e=>{state.filter.pricing=e.target.value;render()});
 $('#cameraBtn')?.addEventListener('click',()=>$('#cameraInput').click());$('#uploadBtn')?.addEventListener('click',()=>$('#uploadInput').click());
 $('#cameraInput')?.addEventListener('change',e=>scanFile(e.target.files?.[0]));$('#uploadInput')?.addEventListener('change',e=>scanFile(e.target.files?.[0]));
 $('#marketSearchBtn')?.addEventListener('click',marketSearchChooser);
 $('#profileSignin')?.addEventListener('click',()=>$('#authDialog').showModal());
 $('#exportBtn')?.addEventListener('click',exportData);
}

function openCardDialog(h=null,prefill=null){const d=$('#cardDialog'),data=h||prefill||{};$('#cardDialogTitle').textContent=h?'Edit holding':'Add card';$('#cardId').value=h?.id||'';const map={category:'category',subject:'subject',year:'year',manufacturer:'manufacturer',brand:'brand',setName:'set_name',cardNumber:'card_number',parallel:'parallel',serialNumber:'serial_number',team:'team',league:'league',condition:'condition',quantity:'quantity',costBasis:'cost_basis',acquisitionSource:'acquisition_source',acquisitionDate:'acquisition_date',manualValue:'manual_value',gradingCompany:'grading_company',grade:'grade',certNumber:'cert_number',notes:'notes'};for(const [id,key] of Object.entries(map)){const el=$('#'+id);el.value=data[key]??(id==='quantity'?1:(id==='condition'?'Raw — unknown':''))}$('#rookie').checked=!!data.rookie;$('#autograph').checked=!!data.autograph;$('#relic').checked=!!data.relic;$('#deleteCardBtn').classList.toggle('hidden',!h);d.showModal()}
function readCardForm(){const get=id=>$('#'+id).value.trim();return {id:get('cardId')||uuid(),category:get('category'),subject:get('subject'),year:get('year'),manufacturer:get('manufacturer'),brand:get('brand'),set_name:get('setName'),card_number:get('cardNumber'),parallel:get('parallel'),serial_number:get('serialNumber'),team:get('team'),league:get('league'),condition:get('condition'),quantity:Number(get('quantity')||1),cost_basis:get('costBasis')===''?'':Number(get('costBasis')),acquisition_source:get('acquisitionSource'),acquisition_date:get('acquisitionDate')||null,manual_value:get('manualValue')===''?'':Number(get('manualValue')),grading_company:get('gradingCompany'),grade:get('grade'),cert_number:get('certNumber'),rookie:$('#rookie').checked,autograph:$('#autograph').checked,relic:$('#relic').checked,notes:get('notes'),updated_at:nowIso()}}
async function saveCardFromForm(){const h=readCardForm();if(!h.subject){toast('Player or character name is required');return}const existing=state.holdings.find(x=>x.id===h.id);if(existing){Object.assign(existing,h)}else{h.created_at=nowIso();if(state.scan?.imageDataUrl)h.image_url=state.scan.imageDataUrl;state.holdings.unshift(h)}if(state.backend==='cloud'&&state.user){let row={...h,image_path:existing?.image_path||null};if(!existing?.image_path&&state.scan?.file){row.image_path=await uploadCardPhoto(state.scan.file)}const {error}=await state.supabase.from('card_holdings').upsert(toDb(row));if(error){toast('Cloud save failed');return}await syncCloud()}else saveLocal();$('#cardDialog').close();state.scan=null;toast(existing?'Holding updated':'Added to portfolio');setView('portfolio')}
async function uploadCardPhoto(file){try{const blob=await compressImage(file,1500,.82),path=`${state.user.id}/${uuid()}.jpg`;const {error}=await state.supabase.storage.from('card-images').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(error)throw error;return path}catch{toast('Card saved without photo');return null}}
async function deleteCurrentCard(){const id=$('#cardId').value;if(!id||!confirm('Delete this holding? This cannot be undone.'))return;if(state.backend==='cloud'&&state.user){const h=state.holdings.find(x=>x.id===id);const {error}=await state.supabase.from('card_holdings').delete().eq('id',id).eq('user_id',state.user.id);if(error){toast('Delete failed');return}if(h?.image_path)await state.supabase.storage.from('card-images').remove([h.image_path]);await syncCloud()}else{state.holdings=state.holdings.filter(x=>x.id!==id);state.snapshots=state.snapshots.filter(x=>x.holding_id!==id);saveLocal()}$('#cardDialog').close();toast('Holding deleted');render()}
