/* Cardfolio supported UI languages. Card identity/marketplace titles are never machine-translated. */
(() => {
  'use strict';
  const KEY='cardfolio.locale.v1';
  const LOCALES={en:{label:'English',lang:'en'},es:{label:'Español',lang:'es'},bn:{label:'বাংলা',lang:'bn'}};
  const D={
    es:{
      'Home':'Inicio','Portfolio':'Portafolio','Scan':'Escanear','Watch':'Seguir','Watchlist':'Lista de seguimiento','Market':'Mercado','Grading':'Calificación','Profile':'Perfil','Sign out':'Cerrar sesión','Sign in':'Iniciar sesión','Manual add':'Agregar manualmente',
      'Scan a card':'Escanear una tarjeta','Open camera':'Abrir escáner','Choose photo':'Elegir foto','Collection':'Colección','By category':'Por categoría','See all':'Ver todo','Assets':'Activos','Recently added':'Añadidas recientemente','Your collection':'Tu colección','Add card':'Agregar tarjeta','All':'Todo','Priced':'Con precio','Unpriced':'Sin precio',
      'Card facts':'Datos de la tarjeta','Exact asset identity':'Identidad exacta del activo','Exact identity':'Identidad exacta','Year':'Año','Set':'Set','Card #':'Tarjeta #','Parallel':'Paralela','Variant':'Variante','Grade':'Grado','Language':'Idioma','Edition':'Edición','Status':'Estado','Player / character':'Jugador / personaje','Manufacturer':'Fabricante','Product':'Producto','Product / set':'Producto / set','Serial':'Serie','Team / club':'Equipo / club','League':'Liga',
      'Market evidence':'Evidencia de mercado','Market activity':'Actividad de mercado','Current':'Actual','Sample':'Muestra','Confidence':'Confianza','Edit holding':'Editar posición','Live marketplace':'Mercado en vivo','Active eBay listings':'Anuncios activos de eBay','Active listings':'Anuncios activos','Sold comps':'Ventas comparables','Pending Price':'Precio pendiente','Raw':'Sin calificar',
      'Card scanner':'Escáner de tarjetas','Center the card inside the frame':'Centra la tarjeta dentro del marco','Hold steady, then capture':'Mantén estable y captura','Retake':'Repetir','Use scan':'Usar escaneo','Capture':'Capturar','Cancel':'Cancelar','Choose language':'Elegir idioma','App language':'Idioma de la app',
      'Account':'Cuenta','Market engine':'Motor de mercado','Hourly research':'Investigación por hora','Continue with Google':'Continuar con Google','Email sign in':'Iniciar con correo','Export JSON':'Exportar JSON','Search a card':'Buscar una tarjeta','No recent cards.':'No hay tarjetas recientes.'
    },
    bn:{
      'Home':'হোম','Portfolio':'পোর্টফোলিও','Scan':'স্ক্যান','Watch':'ওয়াচ','Watchlist':'ওয়াচলিস্ট','Market':'মার্কেট','Grading':'গ্রেডিং','Profile':'প্রোফাইল','Sign out':'সাইন আউট','Sign in':'সাইন ইন','Manual add':'ম্যানুয়ালি যোগ করুন',
      'Scan a card':'কার্ড স্ক্যান করুন','Open camera':'স্ক্যানার খুলুন','Choose photo':'ছবি বেছে নিন','Collection':'কালেকশন','By category':'ক্যাটাগরি অনুযায়ী','See all':'সব দেখুন','Assets':'অ্যাসেট','Recently added':'সম্প্রতি যোগ করা','Your collection':'আপনার কালেকশন','Add card':'কার্ড যোগ করুন','All':'সব','Priced':'দাম আছে','Unpriced':'দাম নেই',
      'Card facts':'কার্ড তথ্য','Exact asset identity':'সঠিক অ্যাসেট পরিচয়','Exact identity':'সঠিক পরিচয়','Year':'বছর','Set':'সেট','Card #':'কার্ড #','Parallel':'প্যারালেল','Variant':'ভ্যারিয়েন্ট','Grade':'গ্রেড','Language':'ভাষা','Edition':'এডিশন','Status':'স্ট্যাটাস','Player / character':'প্লেয়ার / চরিত্র','Manufacturer':'প্রস্তুতকারক','Product':'প্রোডাক্ট','Product / set':'প্রোডাক্ট / সেট','Serial':'সিরিয়াল','Team / club':'টিম / ক্লাব','League':'লিগ',
      'Market evidence':'মার্কেট প্রমাণ','Market activity':'মার্কেট কার্যক্রম','Current':'বর্তমান','Sample':'স্যাম্পল','Confidence':'বিশ্বাসযোগ্যতা','Edit holding':'হোল্ডিং এডিট করুন','Live marketplace':'লাইভ মার্কেটপ্লেস','Active eBay listings':'সক্রিয় eBay লিস্টিং','Active listings':'সক্রিয় লিস্টিং','Sold comps':'বিক্রি হওয়া তুলনা','Pending Price':'দাম অপেক্ষমাণ','Raw':'র',
      'Card scanner':'কার্ড স্ক্যানার','Center the card inside the frame':'কার্ডটি ফ্রেমের মাঝখানে রাখুন','Hold steady, then capture':'স্থির রাখুন, তারপর ক্যাপচার করুন','Retake':'আবার নিন','Use scan':'স্ক্যান ব্যবহার করুন','Capture':'ক্যাপচার','Cancel':'বাতিল','Choose language':'ভাষা বেছে নিন','App language':'অ্যাপের ভাষা',
      'Account':'অ্যাকাউন্ট','Market engine':'মার্কেট ইঞ্জিন','Hourly research':'প্রতি ঘণ্টার গবেষণা','Continue with Google':'Google দিয়ে চালিয়ে যান','Email sign in':'ইমেইল দিয়ে সাইন ইন','Export JSON':'JSON এক্সপোর্ট','Search a card':'কার্ড খুঁজুন','No recent cards.':'সাম্প্রতিক কোনো কার্ড নেই।'
    }
  };
  let locale=localStorage.getItem(KEY)||'en';if(!LOCALES[locale])locale='en';let queued=false;
  const tr=s=>locale==='en'?s:(D[locale]?.[s]||s);
  const skip=node=>!!node.parentElement?.closest('.album-copy strong,.asset-title h1,.holding-name,.evidence-row strong,.embedded-listing-copy strong,[data-no-i18n],script,style,textarea');

  function css(){if(document.getElementById('cardfolio-locale-css'))return;const s=document.createElement('style');s.id='cardfolio-locale-css';s.textContent=`.cardfolio-language-row{cursor:pointer;position:relative;padding-right:44px!important}.cardfolio-language-row:after{content:'›';position:absolute;right:17px;top:50%;transform:translateY(-50%);font-size:27px;color:var(--muted)}.cardfolio-language-row:active{transform:scale(.99)}#cardfolioLanguagePicker{border:0;padding:0;background:transparent;max-width:none;width:min(92vw,520px)}#cardfolioLanguagePicker::backdrop{background:rgba(13,22,32,.30);backdrop-filter:blur(14px)}.cf-language-sheet{border-radius:30px;padding:22px;background:rgba(250,252,255,.97);border:1px solid rgba(255,255,255,.92);box-shadow:0 30px 90px rgba(20,34,50,.22);color:var(--text)}.cf-language-sheet h2{margin:2px 0 5px;font-size:24px}.cf-language-sheet p{margin:0 0 16px;color:var(--muted);font-size:13px;line-height:1.45}.cf-language-options{display:grid;gap:9px}.cf-language-option{width:100%;display:flex;align-items:center;justify-content:space-between;min-height:58px;padding:0 17px;border-radius:18px;border:1px solid rgba(70,95,120,.12);background:#fff;color:var(--text);font-size:16px;font-weight:850}.cf-language-option.selected{outline:2px solid #2389ff;outline-offset:-2px}.cf-language-close{margin-top:13px;width:100%;min-height:52px;border-radius:17px;border:0;background:#101620;color:#fff;font-weight:850;font-size:15px}`;document.head.appendChild(s)}

  function translate(root=document.body){if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(w.nextNode())nodes.push(w.currentNode);for(const n of nodes){if(skip(n))continue;const raw=n.nodeValue||'',trim=raw.trim();if(!trim)continue;if(!n.__cfBase)n.__cfBase=trim;const base=n.__cfBase,next=tr(base),lead=raw.match(/^\s*/)?.[0]||'',tail=raw.match(/\s*$/)?.[0]||'',rendered=lead+next+tail;if(raw!==rendered)n.nodeValue=rendered}root.querySelectorAll?.('input[placeholder],textarea[placeholder]').forEach(e=>{if(!e.dataset.cfPh)e.dataset.cfPh=e.getAttribute('placeholder')||'';const next=tr(e.dataset.cfPh);if(e.getAttribute('placeholder')!==next)e.setAttribute('placeholder',next)})}
  function title(){const e=document.getElementById('viewTitle');if(!e||typeof state==='undefined')return;const base=({home:'Home',portfolio:'Portfolio',scan:'Scan a card',watchlist:'Watchlist',market:'Market',grading:'Grading',profile:'Profile'})[state.view]||'Home',next=tr(base);if(e.textContent!==next)e.textContent=next}
  function label(){return LOCALES[locale]?.label||'English'}

  function languageRow(){const d=document.getElementById('cardDetailDialog');if(!d?.open)return;const rows=[...d.querySelectorAll('.identity-stat-grid > span,.identity-grid > div,.fact-grid > div')];const row=rows.find(r=>{const l=r.querySelector(':scope > small,:scope > span')||r.querySelector('small,span');const base=l?.firstChild?.__cfBase||l?.textContent?.trim();return base==='Language'||l?.textContent?.trim()===tr('Language')});if(!row)return;row.classList.add('cardfolio-language-row');row.setAttribute('role','button');row.setAttribute('tabindex','0');row.setAttribute('aria-label',`${tr('App language')}: ${label()}`);const l=row.querySelector(':scope > small,:scope > span')||row.querySelector('small,span'),v=row.querySelector(':scope > b,:scope > strong')||row.querySelector('b,strong');if(l&&l.textContent!==tr('Language'))l.textContent=tr('Language');if(v){if(v.textContent!==label())v.textContent=label();v.setAttribute('data-no-i18n','1')}}

  function apply(){document.documentElement.lang=LOCALES[locale].lang;title();translate();languageRow();document.dispatchEvent(new CustomEvent('cardfolio:locale-changed',{detail:{locale}}))}
  function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply()})}
  function picker(){let p=document.getElementById('cardfolioLanguagePicker');if(p)return p;p=document.createElement('dialog');p.id='cardfolioLanguagePicker';p.innerHTML='<div class="cf-language-sheet"><h2></h2><p>Only languages with a Cardfolio interface translation are shown here. Card names and marketplace listing titles stay unchanged.</p><div class="cf-language-options"></div><button type="button" class="cf-language-close"></button></div>';document.body.appendChild(p);p.querySelector('.cf-language-close').addEventListener('click',()=>p.close());p.addEventListener('click',e=>{if(e.target===p)p.close()});return p}
  function open(){const p=picker(),o=p.querySelector('.cf-language-options');p.querySelector('h2').textContent=tr('Choose language');p.querySelector('.cf-language-close').textContent=tr('Cancel');o.innerHTML=Object.entries(LOCALES).map(([code,m])=>`<button type="button" class="cf-language-option ${code===locale?'selected':''}" data-cf-locale="${code}"><span>${m.label}</span><span>${code===locale?'✓':''}</span></button>`).join('');o.querySelectorAll('[data-cf-locale]').forEach(b=>b.addEventListener('click',()=>{const code=b.dataset.cfLocale;if(!LOCALES[code])return;locale=code;localStorage.setItem(KEY,code);apply();p.close();try{toast(`${tr('Language')}: ${label()}`)}catch{}}));p.showModal()}

  css();document.addEventListener('click',e=>{const r=e.target.closest?.('.cardfolio-language-row');if(!r)return;e.preventDefault();e.stopPropagation();open()},true);document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest?.('.cardfolio-language-row')){e.preventDefault();open()}});new MutationObserver(queue).observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('DOMContentLoaded',apply);if(document.readyState!=='loading')apply();window.cardfolioSetLocale=code=>{if(LOCALES[code]){locale=code;localStorage.setItem(KEY,code);apply()}};
})();
