function bindGlobalEvents(){
  document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav) setView(nav.dataset.view)});
  $('#quickAdd').addEventListener('click',()=>openCardDialog());
  $('#authButton').addEventListener('click',async()=>{if(state.user){await state.supabase.auth.signOut();toast('Signed out')}else $('#authDialog').showModal()});
  $('#loginBtn').addEventListener('click',()=>auth('login'));$('#signupBtn').addEventListener('click',()=>auth('signup'));
  $('#saveCardBtn').addEventListener('click',saveCardFromForm);$('#deleteCardBtn').addEventListener('click',deleteCurrentCard);
  $('#closeScanReview').addEventListener('click',()=>$('#scanReviewDialog').close());$('#useScanBtn').addEventListener('click',useScanFields);$('#matchPokemonBtn').addEventListener('click',matchPokemon);
}
async function auth(mode){
  if(state.backend!=='cloud'||!state.supabase){$('#authState').textContent='Cloud auth is not configured yet. Local Vault is active.';return}
  const email=$('#authEmail').value.trim(),password=$('#authPassword').value;
  if(!email||password.length<6){$('#authState').textContent='Enter a valid email and a password of at least 6 characters.';return}
  const fn=mode==='login'?state.supabase.auth.signInWithPassword.bind(state.supabase.auth):state.supabase.auth.signUp.bind(state.supabase.auth);
  const {error}=await fn({email,password});$('#authState').textContent=error?error.message:(mode==='login'?'Signed in.':'Account created. Check email if confirmation is enabled.');if(!error&&mode==='login')$('#authDialog').close();
}

function render(){updateAuthButton(); const c=$('#content');if(state.view==='home') c.innerHTML=homeView();if(state.view==='portfolio') c.innerHTML=portfolioView();if(state.view==='scan') c.innerHTML=scanView();if(state.view==='market') c.innerHTML=marketView();if(state.view==='grading') c.innerHTML=gradingView();if(state.view==='profile') c.innerHTML=profileView();bindViewEvents()}
function holdingValue(h){if(Number.isFinite(Number(h.market_value))) return Number(h.market_value)*Number(h.quantity||1);if(h.manual_value!==''&&Number.isFinite(Number(h.manual_value))) return Number(h.manual_value)*Number(h.quantity||1);return 0}
function valued(h){return Number.isFinite(Number(h.market_value))||(h.manual_value!==''&&Number.isFinite(Number(h.manual_value)))}
function metrics(){const priced=state.holdings.filter(valued),value=priced.reduce((a,h)=>a+holdingValue(h),0),cost=state.holdings.reduce((a,h)=>a+(Number(h.cost_basis)||0)*Number(h.quantity||1),0),pnl=value-cost;return{priced,value,cost,pnl,pnlPct:cost?pnl/cost*100:0,total:state.holdings.reduce((a,h)=>a+Number(h.quantity||1),0)}}
function homeView(){
 const m=metrics(),hist=portfolioHistory();return `<div class="hero-grid"><section class="panel portfolio-hero"><div><div class="metric-label">Portfolio market value <span class="source-tag">${m.priced.length} priced / ${state.holdings.length} holdings</span></div><div class="portfolio-value">${money(m.value)}</div><div class="metric-line"><strong class="${m.pnl>=0?'good':'bad'}">${m.pnl>=0?'+':''}${money(m.pnl)}</strong><span class="${m.pnl>=0?'good':'bad'}">${m.pnl>=0?'+':''}${pct(m.pnlPct)} vs cost</span></div></div>${historyChart(hist)}<div class="metric-strip"><div class="mini-metric"><span class="metric-label">Cost basis</span><strong>${money(m.cost)}</strong></div><div class="mini-metric"><span class="metric-label">Cards</span><strong>${m.total}</strong></div><div class="mini-metric"><span class="metric-label">Unpriced</span><strong>${state.holdings.filter(h=>!valued(h)).length}</strong></div></div></section><div class="stack"><section class="panel"><div class="section-head"><h3>Allocation</h3></div>${allocationHtml()}</section><section class="panel"><div class="section-head"><h3>Quick scan</h3></div><p class="muted">Camera → OCR → confirm → portfolio. Nothing is added until you approve it.</p><button class="btn primary" data-view="scan">Scan a card</button></section></div></div><div class="data-grid"><section class="panel" style="grid-column:span 2"><div class="section-head"><h2>Recent holdings</h2><button class="btn secondary" data-view="portfolio">View all</button></div>${holdingList(state.holdings.slice(0,6))}</section><section class="panel"><div class="section-head"><h3>Market integrity</h3></div><p class="muted">Prices are shown only with a source and observation time. Missing market data stays unpriced.</p><div class="tip"><strong>Pokémon</strong><div class="holding-meta">TCGdex → TCGplayer USD when available</div></div><div class="tip"><strong>Sports</strong><div class="holding-meta">eBay live listings when API is configured; otherwise direct market search.</div></div></section></div>`
}
function portfolioHistory(){
 const groups={};for(const s of state.snapshots){const d=(s.observed_at||'').slice(0,10);if(!d)continue;groups[d]=(groups[d]||0)+Number(s.market_value||0)*Number(s.quantity||1)}return Object.entries(groups).sort(([a],[b])=>a.localeCompare(b)).map(([date,value])=>({date,value}))
}
function historyChart(hist){if(hist.length<2)return `<div class="chart-wrap empty"><div>Portfolio history appears after at least two real pricing observations.</div></div><div class="timeline-note">No synthetic backfill.</div>`;const w=600,h=135,vals=hist.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,pts=hist.map((x,i)=>`${i/(hist.length-1)*w},${h-(x.value-min)/span*(h-18)-9}`).join(' ');return `<div class="chart-wrap"><svg class="spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-label="Portfolio history"><polyline points="${pts}" fill="none" stroke="var(--accent)" stroke-width="3" vector-effect="non-scaling-stroke"/></svg></div><div class="timeline-note">Built only from stored price snapshots.</div>`}
function allocationHtml(){const totals={};for(const h of state.holdings){totals[h.category]=(totals[h.category]||0)+holdingValue(h)}const sum=Object.values(totals).reduce((a,b)=>a+b,0);if(!sum)return `<div class="empty">Add priced cards to see allocation.</div>`;return `<div class="allocation-list">${Object.entries(totals).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="allocation-row"><span>${escapeHtml(k)}</span><div class="bar"><i style="width:${Math.max(2,v/sum*100)}%"></i></div><strong>${Math.round(v/sum*100)}%</strong></div>`).join('')}</div>`}
function holdingList(list){if(!list.length)return `<div class="empty"><div class="empty-icon">◇</div><strong>No cards yet</strong><p>Scan or manually add your first physical card.</p></div>`;return `<div class="holding-list">${list.map(h=>`<article class="holding" data-card-id="${escapeHtml(h.id)}">${h.image_url?`<img class="thumb" src="${escapeHtml(h.image_url)}" alt="${escapeHtml(h.subject)}"/>`:`<div class="thumb placeholder">◇</div>`}<div><div class="holding-name">${escapeHtml(h.subject||'Untitled card')}</div><div class="holding-meta">${escapeHtml([h.year,h.manufacturer,h.brand,h.set_name,h.card_number&&'#'+h.card_number].filter(Boolean).join(' · '))}</div></div><div class="value-col"><strong>${valued(h)?money(holdingValue(h)):'Unpriced'}</strong><div class="source-tag">${escapeHtml(h.valuation_source||((h.manual_value!==''&&h.manual_value!=null)?'Manual':'No source'))}</div></div><div class="value-col"><strong>${escapeHtml(h.grading_company?`${h.grading_company} ${h.grade||''}`:'Raw')}</strong><div class="holding-meta">×${Number(h.quantity||1)}</div></div></article>`).join('')}</div>`}
function portfolioView(){const cats=['All',...new Set(state.holdings.map(h=>h.category).filter(Boolean))];const filtered=state.holdings.filter(h=>{const q=state.filter.q.toLowerCase(),text=[h.subject,h.team,h.year,h.manufacturer,h.brand,h.set_name,h.card_number,h.parallel,h.grading_company,h.grade].join(' ').toLowerCase();return(!q||text.includes(q))&&(state.filter.category==='All'||h.category===state.filter.category)&&(state.filter.pricing==='All'||(state.filter.pricing==='Priced'?valued(h):!valued(h)))});return `<section class="panel"><div class="section-head"><div><h2>Your cards</h2><div class="holding-meta">${filtered.length} holdings shown</div></div><button class="btn primary" id="portfolioAdd">Add card</button></div><div class="filters"><input class="search-input" id="portfolioSearch" placeholder="Search player, set, card #…" value="${escapeHtml(state.filter.q)}"/><select id="categoryFilter">${cats.map(x=>`<option ${x===state.filter.category?'selected':''}>${escapeHtml(x)}</option>`).join('')}</select><select id="pricingFilter"><option ${state.filter.pricing==='All'?'selected':''}>All</option><option ${state.filter.pricing==='Priced'?'selected':''}>Priced</option><option ${state.filter.pricing==='Unpriced'?'selected':''}>Unpriced</option></select></div>${holdingList(filtered)}</section>`}
function scanView(){return `<div class="scanner"><section class="camera-zone panel"><div><div class="camera-icon">◎</div><h2>Scan a physical card</h2><p class="muted">Uses on-device OCR first. You review every extracted field before anything enters the portfolio.</p><input id="cameraInput" class="capture-input" type="file" accept="image/*" capture="environment"/><input id="uploadInput" class="capture-input" type="file" accept="image/*"/><div class="button-row" style="justify-content:center"><button id="cameraBtn" class="btn primary">Open camera</button><button id="uploadBtn" class="btn secondary">Choose photo</button></div><div id="scanStatus" class="inline-note"></div></div></section><aside class="scan-tips"><div class="tip"><strong>1 · Fill the frame</strong><p class="holding-meta">Keep the card flat and readable. Avoid glare over the name and card number.</p></div><div class="tip"><strong>2 · OCR is not identity</strong><p class="holding-meta">Sports cards are pre-filled from text. Cardfolio never invents an exact catalog match.</p></div><div class="tip"><strong>3 · Pokémon gets catalog matching</strong><p class="holding-meta">Confirmed names can be matched to the live TCGdex catalog before adding.</p></div><div class="tip"><strong>4 · You confirm</strong><p class="holding-meta">Low-confidence output is highlighted through the review step instead of auto-adding.</p></div></aside></div>`}
function marketView(){return `<div class="market-grid"><section class="panel market-card"><div class="market-logo">◉</div><h3>eBay marketplace</h3><p class="muted">Official Browse API supports current active listing search. Sold-history data is not fabricated.</p><div class="market-status">${state.config?.ebayConfigured?'<span class="good">● API configured</span>':'<span class="muted">● API credentials not configured</span>'}</div><button class="btn primary" id="marketSearchBtn">Search a card</button></section><section class="panel market-card"><div class="market-logo">⚡</div><h3>Pokémon market</h3><p class="muted">TCGdex card responses can include TCGplayer USD and Cardmarket pricing; Cardfolio only auto-aggregates compatible USD observations.</p><div class="market-status"><span class="good">● Public API available</span></div><button class="btn secondary" data-view="portfolio">Open Pokémon cards</button></section><section class="panel market-card"><div class="market-logo">↗</div><h3>External markets</h3><p class="muted">No unsupported marketplace is presented as integrated. Card details always offer direct eBay active and sold-search links.</p><div class="market-status"><span class="muted">● Outbound links only</span></div></section></div><section id="marketResults" class="panel" style="margin-top:16px"><div class="empty">Choose a portfolio card to query live market data.</div></section>`}
function gradingView(){const graders=[['PSA','Official online submission','https://www.psacard.com/submit'],['Beckett / BGS','Official grading submission','https://www.beckett.com/grading/submit'],['CGC Cards','Official submission instructions','https://www.cgccards.com/submit/how-to-submit/']];return `<div class="grading-grid">${graders.map(([name,desc,url])=>`<section class="panel grader-card"><div class="market-logo">◇</div><h3>${name}</h3><p class="muted">${desc}. Grading is performed by ${name}, not Cardfolio.</p><a class="btn primary" href="${url}" target="_blank" rel="noopener noreferrer">Open official site ↗</a></section>`).join('')}</div><section class="panel" style="margin-top:16px"><div class="section-head"><h2>Your graded cards</h2></div>${holdingList(state.holdings.filter(h=>h.grading_company))}</section>`}
function profileView(){const cloud=state.backend==='cloud';return `<div class="hero-grid"><section class="panel"><div class="section-head"><h2>Data & account</h2></div><div class="tip"><strong>${cloud?'Supabase cloud available':'Local Vault active'}</strong><p class="holding-meta">${cloud?(state.user?`Signed in as ${escapeHtml(state.user.email||'user')}. Data is synced per account.`:'Sign in to sync a private portfolio across devices.'):'Your portfolio currently persists in this browser only. Cloud configuration is intentionally not faked.'}</p></div><div class="button-row" style="margin-top:14px">${cloud&&!state.user?'<button class="btn primary" id="profileSignin">Sign in</button>':''}<button class="btn secondary" id="exportBtn">Export JSON</button></div></section><section class="panel"><div class="section-head"><h3>Storage discipline</h3></div><p class="muted">Card photos are compressed. Public catalog images are referenced rather than duplicated. Market refreshes are user-triggered to preserve free-tier capacity.</p><div class="tip"><strong>${state.holdings.length}</strong><div class="holding-meta">holdings in current vault</div></div><div class="tip"><strong>${state.snapshots.length}</strong><div class="holding-meta">real price observations stored</div></div></section></div>`}
